title: "SkyNetHosting Blog"
description: "Guides, case studies, and performance tips from SkyNetHosting."
url: "https://aneesh1985-rgb.github.io"   # change if you don't use custom domain
baseurl: "/blog7"

# Theme: use built-in GitHub Pages-safe plugins
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# SEO / social
logo: /images/logo.png
social:
  name: SkyNetHosting
  links:
    - https://skynethosting.net
